### PR TITLE
Replace deprecated guava method

### PR DESCRIPTION
**Pull request by dhodovsk**
* Since Jenkins 2.320 new version of Guava is used
  - https://www.jenkins.io/blog/2021/11/09/guava-upgrade/
* method com.google.common.base.Objects.firstNonNull(T, T) is deprecated
  - https://guava.dev/releases/19.0/api/docs/deprecated-list.html

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by sturivny** [comment]
Hello,
I'm also interested in this fix.

**Comment by msrb** [comment]
Good catch.

I think this will also require `jenkins.version` bump in pom.xml(s). The problem might be that the new guava is only available in the very latest [LTS 2.332.1](https://www.jenkins.io/changelog-stable/). `MoreObjects` class was added in guava 18.0 and older Jenkins unfortunately bundles prehistoric 11.0.

If the jump to the latest LTS would be too harsh, then maybe we could simply reimplement the `firstNonNull()` method in the plugin (it's a trivial helper function).

**Comment by msrb** [comment]
@olivergondza WDYT?

**Comment by olivergondza** [comment]
All affected methods can be replaced by Jenkins existing helpers: https://github.com/jenkinsci/jms-messaging-plugin/pull/234

**Comment by olivergondza** [comment]
This fix is released as 1.1.27. Thanks for the report.

**Pull request closed without merging**
