### PR TITLE
Add support for Fedora messaging wire format

### PR DESCRIPTION
**Pull request by Zlopez**
Fedora messaging recently introduced wire format (see
https://fedora-messaging.readthedocs.io/en/latest/wire-format.html).
This commit adds support for the new headers.

Signed-off-by: Michal Konečný <mkonecny@redhat.com>

### CODE REVIEW

**Comment by scoheb** [comment]
please rebase

**Comment by Zlopez** [comment]
Rebased

**Comment by scoheb** [comment]
There are test failures. Can you please review them?

**Comment by Zlopez** [comment]
Where can I look at the specific failures?

**Comment by scoheb** [comment]
https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fjms-messaging-plugin/detail/PR-162/3/pipeline

**Comment by Zlopez** [comment]
Sorry, didn't noticed the correct step. Looking at it, this doesn't look like these errors are related to changes in this PR.
```
[2020-02-21T08:58:45.503Z] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 326.961 s <<< FAILURE! - in com.redhat.jenkins.plugins.ci.integration.AmqMessagingPluginLockdownIntegrationTest
[2020-02-21T08:58:45.503Z] [ERROR] com.redhat.jenkins.plugins.ci.integration.AmqMessagingPluginLockdownIntegrationTest.testBlockNonAdminAccess  Time elapsed: 326.875 s  <<< ERROR!
[2020-02-21T08:58:45.503Z] java.lang.IllegalArgumentException: jms-messaging plugin not installed
```

```
[2020-02-21T08:58:45.503Z] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 326.961 s <<< FAILURE! - in com.redhat.jenkins.plugins.ci.integration.AmqMessagingPluginLockdownIntegrationTest
[2020-02-21T08:58:45.503Z] [ERROR] com.redhat.jenkins.plugins.ci.integration.AmqMessagingPluginLockdownIntegrationTest.testBlockNonAdminAccess  Time elapsed: 326.875 s  <<< ERROR!
[2020-02-21T08:58:45.503Z] java.lang.IllegalArgumentException: jms-messaging plugin not installed
```

This looks like some temporary error with plugin installation.

**Comment by Zlopez** [comment]
@scoheb I did a force push to restart the tests and now everything ended with success.

**Comment by scoheb** [comment]
Released in version 1.1.14

**Pull request merged**
