### PR TITLE
Test downgrading Jenkins version

### PR DESCRIPTION
**Pull request by Avielyo10**
For now Jenkins version is 2.176.1, we want to downgrade Jenkins version as low as possible so we can let more users the ability to use the plugin.

### CODE REVIEW

**Comment by Avielyo10** [comment]
@scoheb @ggallen 
Hi this will be very useful for some of our clients :)
Thanks

**Comment by scoheb** [comment]
@olivergondza You ok with this?

**Comment by Avielyo10** [comment]
@scoheb He asked me to do that :)

**Comment by scoheb** [comment]
@Avielyo10 I will release once I merge #179

**Comment by Avielyo10** [comment]
@scoheb Thanks!

**Comment by scoheb** [comment]
@Avielyo10  I can release right away if you cannot wait...

**Comment by Avielyo10** [comment]
@scoheb This can wait, no pressure at all, thanks a lot Scott!

**Comment by scoheb** [comment]
Released in version 1.1.14

**Pull request merged**
