### PR TITLE
Correct handling of Boolean Parameters during triggering

### LINKED ISSUE #141: Boolean parameters are not set by JMS properties
**Environment:**
* A Jenkins Job *A* that has a boolean parameter and is configured to be triggered by a CI message.
* A Jenkins Job *B* (which is actually a pipeline) that sends CI messages.
* JMS Messaging plugin version: 1.1.9
* Jenkins version: 2.121.3

When we send a message from *B* that contains a boolean property, job *A* is triggered but its boolean parameter is not set by the boolean property. The *A*'s boolean parameter is always set to its default value regardless the CI message.

This works for us with string parameters/properties, so this concerns only boolean.

Version 1.1.2 works just fine with boolean parameters.

### PR DESCRIPTION
**Pull request by scoheb**
Fixes #141

### CODE REVIEW

**Comment by ggallen** [comment]
I think I understand what you are doing, but fedmsg doesn't have any concept of message headers.  So I assume you are forcing any parameters to behave as headers?

**Comment by scoheb** [comment]
@ggallen Looking at datagrepper for Fedora (https://apps.fedoraproject.org/datagrepper/id?id=2019-6e63976f-9b4e-4f1d-941e-d950babe8b32&is_raw=true&size=extra-large) there is a headers element...I am using that.

**Comment by ggallen** [comment]
That's something added by datagrepper. It's not part of the actual message at all.  Just as the "msg" element isn't really part of the message, but datagrepper adds that and puts the body of the message under it.

This solution may work, and may be the only way to do it. But I'm not sure it's the right way. I don't think job parameters for AMQ messages get put in the message headers. Or do they?

**Comment by scoheb** [comment]
@ggallen maybe it is not applicable for FedMsg...but it is working...

it has always worked for ActiveMQ for String parameters...I fixed it to work with Booleans

**Pull request merged**
