### PR TITLE
[CID-1380] Deleting project does not unsubscribe job nor shutdown thr…

### PR DESCRIPTION
**Pull request by ggallen**
…ead.

### CODE REVIEW

**Comment by scoheb** [comment]
Shall we add a simple test?

**Comment by ggallen** [comment]
Probably.  Not sure how to test that the thread is gone.  Ideas?

**Comment by scoheb** [comment]
we can maybe test the rename...

- create a job 123 that sends message.
- create job ABC that listens for message.
- trigger 123 and ensure that ABC is executed.
- rename ABC to DEF
- trigger 123 again and ensure DEF is executed.

**Comment by ggallen** [comment]
I don't think this will work.  On rename, the new item ends up having 
the old trigger, with the old trigger thread indexed by the old name. So 
the trigger is there and functional.

Maybe we can search the jenkins logs to insure the old trigger thread is 
unsubscribed and the new one subscribed?

-- Greg

**Comment by scoheb** [comment]
I have a simple test to contribute. But we would need both the start() and stop() to log something so we can check the log.

**Comment by ggallen** [comment]
I don't understand.

**Pull request merged**
