### PR TITLE
CONTRA-767: getMsgId for Fedmsg in jms-messaging plugin discrepancy.

### PR DESCRIPTION
**Pull request by ggallen**

### CODE REVIEW

**Comment by johnbieren** [comment]
Commenting so I get updates for this PR

**Comment by johnbieren** [comment]
Is there any estimate to when this will be merged and included in a plugin that is available from the update sites? I ask because I am wondering if installing the snapshot used to test this on the prod master in the meantime is a good idea

**Comment by johnbieren** [comment]
Hey @ggallen I needed this in the jms-messaging-1.1.2 release.. I merged three large PRs and updated the master expecting this fix was in the release =\

**Comment by ggallen** [comment]
@johnbieren , I am sorry. I thought this changed got merges.  I have just done it.

@scoheb , can we get a new release?

**Comment by scoheb** [comment]
1.1.3 is now making its way onto update centers...

**Pull request merged**
